### ISSUE TITLE
To-do list for Project Part 4

### ISSUE THREAD

**Issue by ericbrisson** [CMPUT301F21T03/Alpha-Apps#91]
**Clean Up UI/Make it look like the Figma storyboard:**
- [x] Profile UI -> Mathew
- [x] Following/Followers UI -> Mathew
- [x] Clean up Boot Screen UI (update storyboard with the new logo) -> Moe
- [x] Clean up log In/ sign up UI -> Moe
- [x] Clean up Add Habits UI  -> Arthur
- [x] Clean up Habit Details UI -> Eric
- [x] Clean up Habit Event Details UI -> Jesse
- [x] Add HabitEvent UI -> Jesse
- [x] Edit HabitEvent UI -> Jesse
- [x] Edit Habit UI -> Eric
- [x] Today Habit UI -> Moe
- [x] All Habits UI -> Moe
- [x] Feed UI -> Eric
- [x] Location UI -> Mathew/Leah

**Bug Fixes:**
- [x] Go back button navigation errors (all of them)  -> Eric
- [x] Make sure all text fields scroll up when keyboard appears

**Testing:**
- [x] Intent testing -> Eric
- [x] Modularize more code for unit testing
- [x] Entity Testing -> Moe

**New Tasks:**
- [x] Images on HabitEvent -> Jesse
- [x] Geolocation on HabitEvent -> Leah
- [ ] Store & calculate how well user sticks to habit
- [x] All Habits list is reorderable -> Eric
- [x] Feed functionality w/ firestore
- [x] Ensure progress bars on habits in sync with data -> Arthur
- [x] Notifications -> Arthur
- [x] (at the end) update the UML diagrams - Arthur
- [ ] Planning the demonstration (what is shown to the customer, script, areas to focus on) -> will do Monday, not necessary for actual deadline
- [x] Update the storyboard to include how to type in someones user ID to request to follow them -> Moe
- [x] User search functionality on Feed page -> Moe
